name: Release
on:
  push:
    branches: [main]
concurrency: ${{ github.workflow }}-${{ github.ref }}
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: install deps
        run: bun install --frozen-lockfile
      - name: create release PR or GitHub releases
        uses: changesets/action@v1
        with:
          version: bun run version-packages
          publish: bunx changeset tag && git push --follow-tags
          createGithubReleases: true
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
