name: Release

on:
  push:
    branches: [main]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install deps
        run: bun install --frozen-lockfile

      - name: create release PR or tag
        id: changesets
        uses: changesets/action@v1
        with:
          version: bun run version-packages
          publish: bunx changeset tag
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create GitHub releases from CHANGELOG
        if: steps.changesets.outputs.published == 'true'
        uses: StafflinePeoplePlus/changeset-github-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
